--see a working simple at http://sqlfiddle.com/#!9/cf9d97/3

CREATE TABLE country (
  id int not null,
  name char(50) not null,
  alpha2code char(2) not null,
  alpha3code char(3) not null,
  constraint country_pk primary key (id)
);

-- data from http://datahub.io/dataset/iso-3166-1-alpha-2-country-codes/resource/9c3b30dd-f5f3-4bbe-a3cb-d7b2c21d66ce
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (4, 'Afghanistan', 'AFG', 'AF');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (8, 'Albania', 'ALB', 'AL');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (12, 'Algeria', 'DZA', 'DZ');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (20, 'Andorra', 'AND', 'AD');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (24, 'Angola', 'AGO', 'AO');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (28, 'Antigua and Barbuda', 'ATG', 'AG');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (32, 'Argentina', 'ARG', 'AR');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (51, 'Armenia', 'ARM', 'AM');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (36, 'Australia', 'AUS', 'AU');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (40, 'Austria', 'AUT', 'AT');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (31, 'Azerbaijan', 'AZE', 'AZ');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (44, 'Bahamas, The', 'BHS', 'BS');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (48, 'Bahrain', 'BHR', 'BH');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (50, 'Bangladesh', 'BGD', 'BD');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (52, 'Barbados', 'BRB', 'BB');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (112, 'Belarus', 'BLR', 'BY');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (56, 'Belgium', 'BEL', 'BE');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (84, 'Belize', 'BLZ', 'BZ');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (204, 'Benin', 'BEN', 'BJ');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (64, 'Bhutan', 'BTN', 'BT');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (68, 'Bolivia', 'BOL', 'BO');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (70, 'Bosnia and Herzegovina', 'BIH', 'BA');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (72, 'Botswana', 'BWA', 'BW');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (76, 'Brazil', 'BRA', 'BR');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (96, 'Brunei', 'BRN', 'BN');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (100, 'Bulgaria', 'BGR', 'BG');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (854, 'Burkina Faso', 'BFA', 'BF');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (108, 'Burundi', 'BDI', 'BI');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (116, 'Cambodia', 'KHM', 'KH');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (120, 'Cameroon', 'CMR', 'CM');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (124, 'Canada', 'CAN', 'CA');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (132, 'Cape Verde', 'CPV', 'CV');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (140, 'Central African Republic', 'CAF', 'CF');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (148, 'Chad', 'TCD', 'TD');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (152, 'Chile', 'CHL', 'CL');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (156, 'China, Peoples Republic of', 'CHN', 'CN');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (170, 'Colombia', 'COL', 'CO');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (174, 'Comoros', 'COM', 'KM');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (180, 'Congo, (Congo  Kinshasa)', 'COD', 'CD');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (178, 'Congo, (Congo  Brazzaville)', 'COG', 'CG');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (188, 'Costa Rica', 'CRI', 'CR');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (384, 'Cote dIvoire (Ivory Coast)', 'CIV', 'CI');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (191, 'Croatia', 'HRV', 'HR');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (192, 'Cuba', 'CUB', 'CU');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (196, 'Cyprus', 'CYP', 'CY');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (203, 'Czech Republic', 'CZE', 'CZ');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (208, 'Denmark', 'DNK', 'DK');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (262, 'Djibouti', 'DJI', 'DJ');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (212, 'Dominica', 'DMA', 'DM');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (214, 'Dominican Republic', 'DOM', 'DO');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (218, 'Ecuador', 'ECU', 'EC');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (818, 'Egypt', 'EGY', 'EG');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (222, 'El Salvador', 'SLV', 'SV');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (226, 'Equatorial Guinea', 'GNQ', 'GQ');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (232, 'Eritrea', 'ERI', 'ER');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (233, 'Estonia', 'EST', 'EE');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (231, 'Ethiopia', 'ETH', 'ET');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (242, 'Fiji', 'FJI', 'FJ');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (246, 'Finland', 'FIN', 'FI');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (250, 'France', 'FRA', 'FR');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (266, 'Gabon', 'GAB', 'GA');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (270, 'Gambia, The', 'GMB', 'GM');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (268, 'Georgia', 'GEO', 'GE');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (276, 'Germany', 'DEU', 'DE');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (288, 'Ghana', 'GHA', 'GH');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (300, 'Greece', 'GRC', 'GR');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (308, 'Grenada', 'GRD', 'GD');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (320, 'Guatemala', 'GTM', 'GT');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (324, 'Guinea', 'GIN', 'GN');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (624, 'Guinea-Bissau', 'GNB', 'GW');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (328, 'Guyana', 'GUY', 'GY');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (332, 'Haiti', 'HTI', 'HT');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (340, 'Honduras', 'HND', 'HN');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (348, 'Hungary', 'HUN', 'HU');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (352, 'Iceland', 'ISL', 'IS');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (356, 'India', 'IND', 'IN');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (360, 'Indonesia', 'IDN', 'ID');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (364, 'Iran', 'IRN', 'IR');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (368, 'Iraq', 'IRQ', 'IQ');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (372, 'Ireland', 'IRL', 'IE');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (376, 'Israel', 'ISR', 'IL');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (380, 'Italy', 'ITA', 'IT');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (388, 'Jamaica', 'JAM', 'JM');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (392, 'Japan', 'JPN', 'JP');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (400, 'Jordan', 'JOR', 'JO');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (398, 'Kazakhstan', 'KAZ', 'KZ');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (404, 'Kenya', 'KEN', 'KE');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (296, 'Kiribati', 'KIR', 'KI');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (408, 'Korea, North', 'PRK', 'KP');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (410, 'Korea, South', 'KOR', 'KR');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (414, 'Kuwait', 'KWT', 'KW');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (417, 'Kyrgyzstan', 'KGZ', 'KG');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (418, 'Laos', 'LAO', 'LA');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (428, 'Latvia', 'LVA', 'LV');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (422, 'Lebanon', 'LBN', 'LB');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (426, 'Lesotho', 'LSO', 'LS');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (430, 'Liberia', 'LBR', 'LR');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (434, 'Libya', 'LBY', 'LY');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (438, 'Liechtenstein', 'LIE', 'LI');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (440, 'Lithuania', 'LTU', 'LT');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (442, 'Luxembourg', 'LUX', 'LU');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (807, 'Macedonia', 'MKD', 'MK');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (450, 'Madagascar', 'MDG', 'MG');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (454, 'Malawi', 'MWI', 'MW');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (458, 'Malaysia', 'MYS', 'MY');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (462, 'Maldives', 'MDV', 'MV');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (466, 'Mali', 'MLI', 'ML');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (470, 'Malta', 'MLT', 'MT');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (584, 'Marshall Islands', 'MHL', 'MH');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (478, 'Mauritania', 'MRT', 'MR');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (480, 'Mauritius', 'MUS', 'MU');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (484, 'Mexico', 'MEX', 'MX');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (583, 'Micronesia', 'FSM', 'FM');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (498, 'Moldova', 'MDA', 'MD');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (492, 'Monaco', 'MCO', 'MC');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (496, 'Mongolia', 'MNG', 'MN');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (499, 'Montenegro', 'MNE', 'ME');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (504, 'Morocco', 'MAR', 'MA');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (508, 'Mozambique', 'MOZ', 'MZ');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (104, 'Myanmar (Burma)', 'MMR', 'MM');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (516, 'Namibia', 'NAM', 'NA');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (520, 'Nauru', 'NRU', 'NR');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (524, 'Nepal', 'NPL', 'NP');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (528, 'Netherlands', 'NLD', 'NL');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (554, 'New Zealand', 'NZL', 'NZ');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (558, 'Nicaragua', 'NIC', 'NI');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (562, 'Niger', 'NER', 'NE');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (566, 'Nigeria', 'NGA', 'NG');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (578, 'Norway', 'NOR', 'NO');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (512, 'Oman', 'OMN', 'OM');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (586, 'Pakistan', 'PAK', 'PK');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (585, 'Palau', 'PLW', 'PW');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (591, 'Panama', 'PAN', 'PA');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (598, 'Papua New Guinea', 'PNG', 'PG');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (600, 'Paraguay', 'PRY', 'PY');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (604, 'Peru', 'PER', 'PE');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (608, 'Philippines', 'PHL', 'PH');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (616, 'Poland', 'POL', 'PL');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (620, 'Portugal', 'PRT', 'PT');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (634, 'Qatar', 'QAT', 'QA');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (642, 'Romania', 'ROU', 'RO');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (643, 'Russia', 'RUS', 'RU');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (646, 'Rwanda', 'RWA', 'RW');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (659, 'Saint Kitts and Nevis', 'KNA', 'KN');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (662, 'Saint Lucia', 'LCA', 'LC');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (670, 'Saint Vincent and the Grenadines', 'VCT', 'VC');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (882, 'Samoa', 'WSM', 'WS');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (674, 'San Marino', 'SMR', 'SM');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (678, 'Sao Tome and Principe', 'STP', 'ST');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (682, 'Saudi Arabia', 'SAU', 'SA');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (686, 'Senegal', 'SEN', 'SN');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (688, 'Serbia', 'SRB', 'RS');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (690, 'Seychelles', 'SYC', 'SC');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (694, 'Sierra Leone', 'SLE', 'SL');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (702, 'Singapore', 'SGP', 'SG');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (703, 'Slovakia', 'SVK', 'SK');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (705, 'Slovenia', 'SVN', 'SI');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (90, 'Solomon Islands', 'SLB', 'SB');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (706, 'Somalia', 'SOM', 'SO');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (710, 'South Africa', 'ZAF', 'ZA');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (724, 'Spain', 'ESP', 'ES');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (144, 'Sri Lanka', 'LKA', 'LK');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (736, 'Sudan', 'SDN', 'SD');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (740, 'Suriname', 'SUR', 'SR');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (748, 'Swaziland', 'SWZ', 'SZ');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (752, 'Sweden', 'SWE', 'SE');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (756, 'Switzerland', 'CHE', 'CH');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (760, 'Syria', 'SYR', 'SY');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (762, 'Tajikistan', 'TJK', 'TJ');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (834, 'Tanzania', 'TZA', 'TZ');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (764, 'Thailand', 'THA', 'TH');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (626, 'Timor-Leste (East Timor)', 'TLS', 'TL');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (768, 'Togo', 'TGO', 'TG');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (776, 'Tonga', 'TON', 'TO');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (780, 'Trinidad and Tobago', 'TTO', 'TT');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (788, 'Tunisia', 'TUN', 'TN');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (792, 'Turkey', 'TUR', 'TR');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (795, 'Turkmenistan', 'TKM', 'TM');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (798, 'Tuvalu', 'TUV', 'TV');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (800, 'Uganda', 'UGA', 'UG');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (804, 'Ukraine', 'UKR', 'UA');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (784, 'United Arab Emirates', 'ARE', 'AE');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (826, 'United Kingdom', 'GBR', 'GB');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (840, 'United States', 'USA', 'US');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (858, 'Uruguay', 'URY', 'UY');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (860, 'Uzbekistan', 'UZB', 'UZ');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (548, 'Vanuatu', 'VUT', 'VU');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (336, 'Vatican City', 'VAT', 'VA');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (862, 'Venezuela', 'VEN', 'VE');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (704, 'Vietnam', 'VNM', 'VN');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (887, 'Yemen', 'YEM', 'YE');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (894, 'Zambia', 'ZMB', 'ZM');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (716, 'Zimbabwe', 'ZWE', 'ZW');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (268, 'Abkhazia', 'GEO', 'GE');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (158, 'China, Republic of (Taiwan)', 'TWN', 'TW');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (31, 'Nagorno-Karabakh', 'AZE', 'AZ');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (196, 'Northern Cyprus', 'CYP', 'CY');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (498, 'Pridnestrovie (Transnistria)', 'MDA', 'MD');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (706, 'Somaliland', 'SOM', 'SO');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (268, 'South Ossetia', 'GEO', 'GE');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (36, 'Ashmore and Cartier Islands', 'AUS', 'AU');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (162, 'Christmas Island', 'CXR', 'CX');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (166, 'Cocos (Keeling) Islands', 'CCK', 'CC');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (36, 'Coral Sea Islands', 'AUS', 'AU');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (334, 'Heard Island and McDonald Islands', 'HMD', 'HM');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (574, 'Norfolk Island', 'NFK', 'NF');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (540, 'New Caledonia', 'NCL', 'NC');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (258, 'French Polynesia', 'PYF', 'PF');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (175, 'Mayotte', 'MYT', 'YT');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (312, 'Saint Barthelemy', 'GLP', 'GP');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (312, 'Saint Martin', 'GLP', 'GP');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (666, 'Saint Pierre and Miquelon', 'SPM', 'PM');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (876, 'Wallis and Futuna', 'WLF', 'WF');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (260, 'French Southern and Antarctic Lands', 'ATF', 'TF');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (258, 'Clipperton Island', 'PYF', 'PF');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (74, 'Bouvet Island', 'BVT', 'BV');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (184, 'Cook Islands', 'COK', 'CK');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (570, 'Niue', 'NIU', 'NU');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (772, 'Tokelau', 'TKL', 'TK');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (831, 'Guernsey', 'GGY', 'GG');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (833, 'Isle of Man', 'IMN', 'IM');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (832, 'Jersey', 'JEY', 'JE');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (660, 'Anguilla', 'AIA', 'AI');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (60, 'Bermuda', 'BMU', 'BM');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (86, 'British Indian Ocean Territory', 'IOT', 'IO');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (92, 'British Virgin Islands', 'VGB', 'VG');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (136, 'Cayman Islands', 'CYM', 'KY');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (238, 'Falkland Islands (Islas Malvinas)', 'FLK', 'FK');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (292, 'Gibraltar', 'GIB', 'GI');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (500, 'Montserrat', 'MSR', 'MS');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (612, 'Pitcairn Islands', 'PCN', 'PN');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (654, 'Saint Helena', 'SHN', 'SH');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (239, 'South Georgia & South Sandwich Islands', 'SGS', 'GS');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (796, 'Turks and Caicos Islands', 'TCA', 'TC');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (580, 'Northern Mariana Islands', 'MNP', 'MP');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (630, 'Puerto Rico', 'PRI', 'PR');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (16, 'American Samoa', 'ASM', 'AS');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (581, 'Baker Island', 'UMI', 'UM');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (316, 'Guam', 'GUM', 'GU');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (581, 'Howland Island', 'UMI', 'UM');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (581, 'Jarvis Island', 'UMI', 'UM');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (581, 'Johnston Atoll', 'UMI', 'UM');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (581, 'Kingman Reef', 'UMI', 'UM');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (581, 'Midway Islands', 'UMI', 'UM');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (581, 'Navassa Island', 'UMI', 'UM');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (581, 'Palmyra Atoll', 'UMI', 'UM');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (850, 'U.S. Virgin Islands', 'VIR', 'VI');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (850, 'Wake Island', 'UMI', 'UM');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (344, 'Hong Kong', 'HKG', 'HK');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (446, 'Macau', 'MAC', 'MO');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (234, 'Faroe Islands', 'FRO', 'FO');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (304, 'Greenland', 'GRL', 'GL');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (254, 'French Guiana', 'GUF', 'GF');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (312, 'Guadeloupe', 'GLP', 'GP');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (474, 'Martinique', 'MTQ', 'MQ');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (638, 'Reunion', 'REU', 'RE');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (248, 'Aland', 'ALA', 'AX');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (533, 'Aruba', 'ABW', 'AW');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (530, 'Netherlands Antilles', 'ANT', 'AN');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (744, 'Svalbard', 'SJM', 'SJ');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (10, 'Australian Antarctic Territory', 'ATA', 'AQ');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (10, 'Ross Dependency', 'ATA', 'AQ');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (10, 'Peter I Island', 'ATA', 'AQ');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (10, 'Queen Maud Land', 'ATA', 'AQ');
INSERT INTO country (id, name, alpha3code, alpha2code) VALUES (10, 'British Antarctic Territory', 'ATA', 'AQ');
